Repository GameBridgeAI/ts_serialize, pull requests merged in 2020-11, with the labels that each got.

#65 deno@1.5.1 and std@0.76
  .github/workflows/scripts/build.sh
  .github/workflows/ts_serialize_release.yml
  .github/workflows/ts_serialize_tests.yml
  CHANGELOG.md
  examples/deno/deno.ts
  examples/deno/deps.ts
  examples/node/node.ts
  from_json/as_test.ts
  from_json/date_test.ts
  mod.ts
  mod_test.ts
  serializable_test.ts
  serialize_property.ts
  serialize_property_options_map_test.ts
  serialize_property_test.ts
  test_deps.ts
  test_deps_test.ts
  to_json/default_test.ts
  to_json/recursive.ts
  to_json/recursive_test.ts
  tsconfig.json
Labels: CI, enhancement, v1.0.0 roadmap

#66 tsTransformKey functionality
  .github/workflows/scripts/npm_release_files/ts_serialize.d.ts
  CHANGELOG.md
  README.md
  examples/deno/deno.ts
  examples/deno/deps.ts
  examples/node/node.ts
  mod.ts
  serializable.ts
  serializable_test.ts
  serialize_property.ts
Labels: enhancement, v1.0.0 roadmap

#68 fixes #62
  CHANGELOG.md
  serializable.ts
  serialize_property_test.ts
Labels: bug, enhancement, v1.0.0 roadmap

#69 fixes #64
  CHANGELOG.md
  from_json/as.ts
  from_json/as_test.ts
Labels: bug, enhancement, v1.0.0 roadmap

#70 fix builds
  .github/workflows/scripts/npm_release_files/babel_ts_serialize.ts
Labels: CI, bug, v1.0.0 roadmap

#73 use child process to make bundles over unstable programmatic way
  .github/workflows/scripts/build.sh
  .github/workflows/scripts/npm_release_files/babel_ts_serialize.ts
  .github/workflows/scripts/npm_release_files/create_npm_package_file.sh
Labels: CI, bug, v1.0.0 roadmap

#58 Serialized key function
  CHANGELOG.md
  README.md
  serialize_property.ts
  serialize_property_test.ts
Labels: enhancement, question, v1.0.0 roadmap

#61 Add JSON types
  CHANGELOG.md
  from_json/as.ts
  from_json/as_test.ts
  from_json/date.ts
  serializable.ts
  serialize_property_test.ts
  to_json/recursive.ts
Labels: documentation, v1.0.0 roadmap

#74 remove test targets
  .github/workflows/scripts/npm_release_files/babel_ts_serialize.ts
Labels: CI

#78 github pages
  .github/DEVELOPMENT.md
  .github/workflows/scripts/npm_release_files/ts_serialize.d.ts
  .github/workflows/ts_serialize_release.yml
  .github/workflows/ts_serialize_tests.yml
  CHANGELOG.md
  README.md
  _config.yml
  docs/_config.yml
  docs/index.md
  docs/installing.md
  docs/serializable.md
  docs/strategies.md
  docs/transforming.md
  examples/deno/README.md
  from_json/default.ts
  from_json/default_test.ts
  serializable.ts
  serialize_property.ts
  serialize_property_options_map_test.ts
  serialize_property_test.ts
  test_deps.ts
  test_deps_test.ts
  tsconfig.json
Labels: CI, documentation, enhancement, v1.0.0 roadmap

#79 date updates
  .github/workflows/scripts/npm_release_files/ts_serialize.d.ts
  CHANGELOG.md
  docs/installing.md
  docs/strategies.md
  examples/deno/deno.ts
  examples/deno/deps.ts
  examples/node/node.ts
  from_json/date.ts
  from_json/date_test.ts
  mod.ts
  mod_test.ts
  serializable.ts
Labels: bug, enhancement, v1.0.0 roadmap

#85 Fix empty class serialization
  CHANGELOG.md
  serializable.ts
  serialize_property_test.ts
Labels: bug, v1.0.0 roadmap

#82 #80 Polymporphic deserialization
  .github/workflows/scripts/npm_release_files/ts_serialize.d.ts
  CHANGELOG.md
  README.md
  docs/index.md
  docs/polymorphism.md
  mod.ts
  mod_test.ts
  polymorphic/polymorphic.ts
  polymorphic/polymorphic_test.ts
  serializable.ts
Labels: documentation, enhancement, v1.0.0 roadmap

#84 added tsSerialize() exposing toPojo, clean up types, rename Json -> JSON program wide
  .github/CODEOWNERS
  .github/DEVELOPMENT.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/scripts/build.sh
  .github/workflows/scripts/npm_release_files/ts_serialize.d.ts
  .github/workflows/ts_serialize_release.yml
  .github/workflows/ts_serialize_tests.yml
  CHANGELOG.md
  README.md
  docs/index.md
  docs/installing.md
  docs/polymorphism.md
  docs/serializable.md
  docs/strategies.md
  docs/transforming.md
  error_messages.ts
  error_messages_test.ts
  examples/deno/deno.ts
  examples/deno/deps.ts
  examples/fixtures/from.json
  examples/fixtures/to.json
  examples/node/node.ts
  from_json/as.ts
  from_json/default_test.ts
  mod.ts
  mod_test.ts
  polymorphic.ts
  polymorphic_test.ts
  serializable.ts
  serializable_test.ts
  serialize_property.ts
  serialize_property_options_map.ts
  serialize_property_options_map_test.ts
  serialize_property_test.ts
  strategy/compose_strategy.ts
  strategy/compose_strategy_test.ts
  strategy/from_json/date.ts
  strategy/from_json/date_test.ts
  strategy/from_json/default.ts
  strategy/from_json/default_test.ts
  strategy/from_json/to_serializable.ts
  strategy/from_json/to_serializable_test.ts
  strategy/to_json/default.ts
  strategy/to_json/default_test.ts
  strategy/to_json/recursive.ts
  strategy/to_json/recursive_test.ts
  test_deps.ts
  to_json/default_test.ts
  to_json/recursive_test.ts
Labels: breaking changes, documentation, enhancement, v1.0.0 roadmap

#87 RC updates
  CHANGELOG.md
  docs/blog.md
  docs/installing.md
  docs/polymorphism.md
  docs/serializable.md
  docs/strategies.md
  docs/transforming.md
  serializable_test.ts
Labels: documentation, v1.0.0 roadmap
