Repository GameBridgeAI/ts_serialize, pull requests merged in 2022-04, with the labels that each got.

#144 Test markdown code blocks
  .github/test_markdown.ts
  .github/workflows/ts_serialize_release.yml
  .github/workflows/ts_serialize_tests.yml
  CHANGELOG.md
  README.md
Labels: documentation, enhancement, CI, chore, review

#145 Improve transpiling to node
  .github/node_tests/README.md
  .github/node_tests/fixtures/from.json
  .github/node_tests/fixtures/to.json
  .github/node_tests/node_tests.ts
  .github/node_tests/package.json
  .github/node_tests/tsconfig.json
  .github/workflows/scripts/build.sh
  .github/workflows/scripts/build_npm.ts
  .github/workflows/scripts/npm_release_files/babel_ts_serialize.ts
  .github/workflows/scripts/npm_release_files/create_npm_package_file.sh
  .github/workflows/scripts/npm_release_files/create_npm_package_file_test.sh
  .github/workflows/ts_serialize_release.yml
  .github/workflows/ts_serialize_tests.yml
  .gitignore
  CHANGELOG.md
  polymorphic_test.ts
  test_deps.ts
  test_deps_test.ts
Labels: enhancement, review

#146 V2 polish
  .github/test_markdown.ts
  .github/workflows/scripts/build_npm.ts
  .github/workflows/scripts/npm_release_files/ts_serialize.d.ts
  .github/workflows/ts_serialize_release.yml
  .github/workflows/ts_serialize_tests.yml
  CHANGELOG.md
  README.md
  _build_npm.ts
  polymorphic.ts
  polymorphic_test.ts
  serializable.ts
  serialize_property_test.ts
  strategy/from_json/to_object_containing.ts
  strategy/from_json/to_serializable.ts
  strategy/from_json/to_serializable_test.ts
Labels: documentation, enhancement, CI, breaking changes, chore, review

#148 Add missing npm-build dependancy
  _build_npm.ts
Labels: bug, CI, review

#149 Add changelog entries for npm release fix tags
  CHANGELOG.md
Labels: documentation, review
